language: node_js
notifications:
  email: false
jobs:
  include:
    - stage: test
      node_js: 6
      script:
        - npm run test
        - npm run build
    - node_js: 8
      script:
        - npm run test
        - npm run build
    - node_js: 10
      script:
        - npm run test
        - npm run build
    - node_js: 12
      script:
        - npm run lint:commit-travis
        - npm run lint
        - npm run test
        - npm run build
    - stage: publish
      if: branch = master AND type = push AND fork = false
      node_js: 12
      env:
        GITHUB_NAME: "Avi Sharvit"
        GITHUB_EMAIL: sharvita@gmail.com
      before_install: ./scripts/prepare-deploy-ci.sh
      before_script: npm run publish:git-version
      script: npm run build
      deploy:
        provider: script
        skip_cleanup: true
        script: npm run publish:npm
